/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.sgs.mgmt.model.Greeting;

public class EmployeeTest {
    @Test public void testSomeLibraryMethod() {
    	String msg = "Hi I am Amol.";
        Greeting classUnderTest = new Greeting(10, msg);
        assertTrue("someLibraryMethod should return 'true'", msg.equals(classUnderTest.getContent()));
    }
}
